FROM golang:1.19

RUN apt-get update && apt-get install -y lsof && apt-get install -y wget

RUN	wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-arm64 \
    && chmod +x tailwindcss-linux-arm64 \
    && mv tailwindcss-linux-arm64 /usr/local/bin/tailwindcss

ARG app_name
ARG build_number
ARG version
ENV env_build_number=${build_number}
ENV env_version=${version}
ENV GO111MODULE=on
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

RUN mkdir -p /go/src/github.com/Blackmocca/wedding-ui
WORKDIR /go/src/github.com/Blackmocca/wedding-ui

# Move to project folder
WORKDIR /go/src/github.com/Blackmocca/wedding-ui

COPY . . 
RUN go get -u github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon
RUN go mod tidy    

RUN GOARCH=wasm GOOS=js go build -o ./build/web/app.wasm main.go
RUN go build -o ./build/app main.go

EXPOSE 8080

ENTRYPOINT CompileDaemon -include=go.mod -log-prefix=false -color=true --exclude-dir=resources -build="make -B build" -command="make -B run" 
